apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: winov-data
  namespace: winovk8s
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: winov-data
  resources:
    requests:
      storage: 2Gi
  volumeName: winov-data
