{{- define "cm" }}
{{- $service := .service }}
{{- $namespace := .namespace }}
{{- $variables := .variables}}
{{- if $service.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $service.name }}
  namespace: {{ $namespace }}

data:
  {{- if eq $service.name "nginx" }}
  nginx.conf: |
{{ index $variables.configMap.nginx "nginx_conf" | indent 4}}
  server.conf: |
{{ index $variables.configMap.nginx "server_conf" | indent 4}}
  proxy_params: |
{{ index $variables.configMap.nginx "proxy_params" | indent 4}}
  {{- end }}

{{- end }}
{{- end }}

{{- range $service := $.Values.microservices }}
  {{- include "cm" (dict  "service" $service "namespace" $.Values.namespace "variables" $.Values.variables) }}
{{ end }}
