namespace: winovk8s

microservices:
  nginx:
    name: nginx
    enabled: true
    # replicas: 3
    image: nginx:latest
    imagePullPolicy:  IfNotPresent
    hpaCpu: 90
    hpaMemory: 90
    containerPort: 80
    port: 80
    targetPort: 80
    nodePort:
      enabled: true
      externalPort: 30080
    ingress:
      enabled: false
    command:
      enabled: false
    hpaReplicas:
      min: 1
      max: 1
    cpu:
      min: 0.1
      max: 1.0
    memory:
      min: 100Mi
      max: 500Mi
    persistentVolume:
      enabled: true
    extraConfigs:
      enabled: true
      volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: server-conf
          mountPath: /etc/nginx/conf.d/server.conf
          subPath: server.conf
        - name: proxy-params
          mountPath: /etc/nginx/proxy_params
          subPath: proxy_params
      volumes:
        - name: nginx-conf
          key: nginx.conf
          path: nginx.conf
        - name: server-conf
          key: server.conf
          path: server.conf
        - name: proxy-params
          key: proxy_params
          path: proxy_params
    affinity:
      enabled: false
    probes:
      enabled: false

variables:
  configMap:
    nginx:

      nginx_conf: |
        user                        www-data;
        worker_processes            auto;
        worker_rlimit_nofile        65535;

        pcre_jit                    on;

        error_log                   /var/log/nginx/error.log warn;
        include                     /etc/nginx/modules-enabled/*.conf;


        events {
            multi_accept            on;
            worker_connections      2048;
        }

        http {

            charset                 utf-8;
            sendfile                on;
            tcp_nopush              on;
            tcp_nodelay             on;
            server_tokens           off;
            log_not_found           off;
            types_hash_max_size     2048;
            types_hash_bucket_size  64;
            client_max_body_size    100M;

            include                 /etc/nginx/mime.types;
            default_type            application/octet-stream;

            proxy_cache             off;
            fastcgi_cache           off;
            uwsgi_cache             off;
            scgi_cache              off;

            limit_req_zone          $binary_remote_addr zone=limit_zone_1:10m rate=100r/s;

            log_format custom_log_format '$remote_addr - $remote_user [$time_local] '
                            ' "$request" $status $body_bytes_sent '
                            ' "$http_referer" '
                            ' "$http_x_forwarded_for" ';

            access_log              /var/log/nginx/access.log custom_log_format;

            ssl_session_timeout     1d;
            ssl_session_cache       shared:SSL:10m;
            ssl_session_tickets     off;

            ssl_protocols           TLSv1.2 TLSv1.3;
            ssl_ciphers             ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;

            ssl_stapling            on;
            ssl_stapling_verify     on;
            resolver                1.1.1.1 1.0.0.1 [2606:4700:4700::1111] [2606:4700:4700::1001] 8.8.8.8 8.8.4.4 [2001:4860:4860::8888] [2001:4860:4860::8844] 208.67.222.222 208.67.220.220 [2620:119:35::35] [2620:119:53::53] valid=60s;
            resolver_timeout        2s;

            map $http_upgrade $connection_upgrade {
                default upgrade;
                ""      close;
            }

            map $remote_addr $proxy_forwarded_elem {

                ~^[0-9.]+$        "for=$remote_addr";

                ~^[0-9A-Fa-f:.]+$ "for=\"[$remote_addr]\"";

                default           "for=unknown";
            }

            map $http_forwarded $proxy_add_forwarded {

                "~^(,[ \\t]*)*([!#$%&'*+.^_`|~0-9A-Za-z-]+=([!#$%&'*+.^_`|~0-9A-Za-z-]+|\"([\\t \\x21\\x23-\\x5B\\x5D-\\x7E\\x80-\\xFF]|\\\\[\\t \\x21-\\x7E\\x80-\\xFF])*\"))?(;([!#$%&'*+.^_`|~0-9A-Za-z-]+=([!#$%&'*+.^_`|~0-9A-Za-z-]+|\"([\\t \\x21\\x23-\\x5B\\x5D-\\x7E\\x80-\\xFF]|\\\\[\\t \\x21-\\x7E\\x80-\\xFF])*\"))?)*([ \\t]*,([ \\t]*([!#$%&'*+.^_`|~0-9A-Za-z-]+=([!#$%&'*+.^_`|~0-9A-Za-z-]+|\"([\\t \\x21\\x23-\\x5B\\x5D-\\x7E\\x80-\\xFF]|\\\\[\\t \\x21-\\x7E\\x80-\\xFF])*\"))?(;([!#$%&'*+.^_`|~0-9A-Za-z-]+=([!#$%&'*+.^_`|~0-9A-Za-z-]+|\"([\\t \\x21\\x23-\\x5B\\x5D-\\x7E\\x80-\\xFF]|\\\\[\\t \\x21-\\x7E\\x80-\\xFF])*\"))?)*)?)*$" "$http_forwarded, $proxy_forwarded_elem";

                default "$proxy_forwarded_elem";
            }

            autoindex               off;

            gzip                    on;
            gzip_disable            "msie6";

            gzip_min_length         10;
            gzip_proxied            any;
            gzip_comp_level         9;
            gzip_buffers            15 8k;
            gzip_http_version       1.1;
            gzip_types              text/plain text/css application/json application/javascript application/x-javascript text/xml application/xml application/xml+rss text/javascript;

            keepalive_timeout       60;

            include                 /etc/nginx/conf.d/*.conf;
        }

      proxy_params: |
        proxy_set_header Upgrade            $http_upgrade;
        proxy_set_header Connection         $connection_upgrade;
        proxy_set_header X-Real-IP          $remote_addr;
        proxy_set_header Forwarded          $proxy_add_forwarded;
        proxy_set_header X-Forwarded-For    $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto  $scheme;
        proxy_set_header X-Forwarded-Host   $host;
        proxy_set_header X-Forwarded-Port   $server_port;
        proxy_set_header Host 		          $host;

      server_conf: |
        server {
            listen                                  80;
            listen                                  [::]:80;
            server_name                             _; # All domains and IPs

            add_header X-XSS-Protection             "1; mode=block" always;
            add_header X-Content-Type-Options       "nosniff" always;
            add_header Referrer-Policy              "no-referrer-when-downgrade" always;
            add_header Content-Security-Policy      "default-src 'self' http: https: ws: wss: data: blob: 'unsafe-inline'; frame-ancestors 'self';" always;
            add_header Permissions-Policy           "interest-cohort=()" always;
            add_header Strict-Transport-Security    "max-age=31536000; includeSubDomains; preload" always;

            location  / {
                proxy_pass                          http://10.0.1.10:30081;
                include                             /etc/nginx/proxy_params;
                access_log                          /var/log/nginx/access.log custom_log_format;
                error_log                           /var/log/nginx/error.log error;
                limit_req                           zone=limit_zone_1 burst=100 nodelay;
                limit_req_status                    429;
            }
        }

consul:
  server:
    persistentVolume:
      enabled: true
      persistentVolumeConfig:
        - name: data-winovk8s-consul-server-0
          storage: 10Gi
          type: nfs
          server: 10.0.1.10
          path: /nfs/winov-data
  ui:
    service:
      enabled: true
      type: NodePort
      nodePort:
        http: 30081
        https: 30445
